version: '3'
services:
  web:
    build: .
    ports:
     - "80:80"
    depends_on:
     - "couchdb"
  couchdb:
    image: "couchdb:2.1.1"
    ports:
     - "5984:5984"
    volumes:
     - /opt/couchdb/data
networks:
  default:
    external:
      name: api-services-network