version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - "couchdb"
    environment:
     - ASPNETCORE_URLS=http://*:8080
  couchdb:
    image: "couchdb:2.1.1"
    ports:
     - "5984:5984"
    volumes:
     - /opt/couchdb/data
networks:
  default:
    external:
      name: api-services-network