export const TOGGLE_EXPAND_MENU_ITEM = 'TOGGLE_EXPAND_MENU_ITEM'

export const CLOSE_MENU = 'CLOSE_MENU'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const TOGGLE_WITHOUT_ANIMATION = 'TOGGLE_WITHOUT_ANIMATION'

export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED'

export const SET_TOKEN = 'SET_TOKEN'

export const SET_USER = 'SET_USER'

export const LOGIN = 'LOGIN'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT = 'LOGOUT'
